### ISSUE TITLE
Speed up probabilistic interleaving

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#10]

**Comment by mpkato** [comment]
I tried to speed up probabilistic interleaving, but could not achieve improvement over the current implementation ...

**Comment by tmanabe** [comment]
Implementation in C++ may be the best... (and can wait)
https://docs.python.org/3/extending/extending.html

**Comment by mpkato** [comment]
It turned out that `evaluate` is very slow.

**Comment by mpkato** [comment]
Probably solved at #49
