### ISSUE TITLE
Output of InterleavingMethod.evaluate

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#14]
Is it OK if the output of InterleavingMethod.evaluate is changed to a list where each element (i,j) indicates i won j?

Current:
```
Return one of the following tuples:
- (1, 0): Ranking 'a' won
- (0, 1): Ranking 'b' won
- (0, 0): Tie
```

Expected:
```
Return a list of pairs of ranker indices in which element (i, j) indicates i won j.
e.g. a result [(1, 0), (2, 1), (2, 0)]  indicates ranker 1 won ranker 0, and ranker 2 won rankers 0 as well as 1.
```

**Comment by tmanabe** [comment]
Returning richer information is a good idea.
But, how about returning a 2-dimensional array A
where A[i][j] indicates which ranker won (i.e., -1, 0, or 1)?
This is like the preference matrix defined in Schuth+, CIKM 2014.

**Comment by mpkato** [comment]
I first came up with such output. However, it can be very redundant since the matrix is usually very sparse, although this is not strong preference.

**Comment by tmanabe** [comment]
I see.
