### ISSUE TITLE
Proposal for revising MultileavingMethod

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#16]
The current implementation generates an interleaved ranking when two rankings are given.
This may not be convenient when
1. The method requires much time and can save it by caching, and 
2. The distribution of rankings is necessary (e.g. Store the results in a file and use them for some purposes).

A proposal here is to obtain two or more ranking through __init__, compute the distribution in the initialization, and return a ranking if the interleave method is called (without any argument).
Moreover, we can return a dict or a list of tuples that includes all the possible rankings with their probability.

If computing the probability or generating all the possible rankings is not feasible, we can just receive two or more rankings in the initialization, and generate a ranking when the interleave method is called.

**Comment by mpkato** [comment]
It seems that listing up all possible rankings is infeasible. Instead, we can sample rankings with constraints as can be seen in cikm 2015 paper

**Comment by tmanabe** [comment]
I agree.
# Is it common in Python to declare an init method besides the __init__ method?

**Comment by mpkato** [comment]
Sorry, not 2015, but 2014: see Section 4.2.1 of "Multileaved Comparisons for Fast Online Evaluation"

**Comment by tmanabe** [comment]
I see.

**Comment by mpkato** [comment]
Here is a concrete proposal:

```python
class InterleavingMethod(object):
    '''
    Interleaving
    '''
    def __init__(self, max_length, *lists, sample_num=None):
        '''
        max_length: the maximum length of resultant interleaving
        *lists: lists of document IDs
        sample_num: If this is None, an interleaved ranking is generated
                    every time when `interleave` is called.
                    Otherwise, `sample_num` rankings are sampled in the
                    initialization.
        '''

    def interleave(self):
        '''
        Return an instance of Ranking
        '''
        raise NotImplementedError()

    @property
    def ranking_distribution(self):
        '''
        Return a dict of Ranking and its probability
        if rankings are sampled in the initialization.
        Otherwise, return None.
        '''
        raise NotImplementedError()

    def evaluate(self, ranking, clicks):
        '''
        ranking: an instance of Ranking generated by Balanced.interleave
        clicks: a list of indices clicked by a user

        Return a list of pairs of ranker indices
        in which element (i, j) indicates i won j.

        e.g. a result [(1, 0), (2, 1), (2, 0)] indicates
        ranker 1 won ranker 0, and ranker 2 won ranker 0 as well as ranker 1.
        '''
        raise NotImplementedError()
```

**Comment by mpkato** [comment]
Here is a commit that previews the changes:

7e064bf964cd83c6993d98c36e43f367eaa5b871

**Comment by tmanabe** [comment]
LGTM. Here are some comments:
1. How about defining sample(self, sample_num) ?
I think that generating some rankings is not a part of initialization.
2. Why is the ranking_distribution a @property ?
In other words, what are use cases of the setter and the deleter of the ranking_distribution?

**Comment by mpkato** [comment]
1. Can you talk more about the sample(self, sample_num) function?
Is it equivalent to repeat `interleave` method `sample_num` times?

2. Sorry, I though this can enable read-only property. What is a correct way to realize "read-only property"?

**Comment by mpkato** [comment]
For 1, I show some use cases below:
```
import interleave as il

# Balanced(max_length, sample_num, *lists)
# when sample_num is not None
b = il.Balanced(2, 100, [1, 2], [2, 3]) # randomly generate 100 rankings at the initialization
ranking = b.interleave() # sample a ranking from the sampled 100 rankings

# when sample_num is None
b = il.Balanced(2, None, [1, 2], [2, 3]) # no sampling at the initialization
ranking = b.interleave() # randomly generate a ranking
```

**Comment by tmanabe** [comment]
1. I understand. I thought that `__init__` and `interleave` generate rankings independently. 

2. I'm sorry that I thought that @property automatically generates its setter and deleter as well as its getter. (In Ruby, attr_accessor does...)

**Comment by mpkato** [comment]
Thank you for the discussion. I'll then make a pull request.
