### ISSUE TITLE
A little speed up for Probablistic

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#19]
I tried speed up Probablistic. Can you try this?

**Comment by mpkato** [comment]
Here is a code: d8fc2b84e3c6afb867c84f7c07eb6fa15ef0e7df

**Comment by mpkato** [comment]
This must be a bug, let me fix it

**Comment by mpkato** [comment]
I've committed a bug fix for the error: 1f6cb2e9dcd09169262551a6064a6bf479cf3684

**Comment by tmanabe** [comment]
LGTM!
Small comment: The 19th line of `tests/test_probabilistic_interleave.py` should be removed?

**Comment by mpkato** [comment]
Thanks, I deleted it.

364ef52ae02c3bdef20785a72b46281f9d5a424a

**Comment by mpkato** [comment]
Previous version: ~ 30sec
Current version: ~ 28sec

Small improvement.
