### ISSUE TITLE
Discussion on the arguments in InterleavingMethod

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#22]
Sorry for trying to change the arguments in InterleavingMethod again.

The current arguments of InterleavingMethod are: 
```python
def __init__(self, max_length, sample_num, *lists)
```

This could be improved since **keyword arguments with default values cannot be used with a variable-length argument**.

There are some options:
```python
def __init__(self, max_length, lists, sample_num=None, some_keyword_argument=3)
```
(`lists` is no longer a variable-length argument)

```python
def __init__(self, max_length, *lists, **kwargs)
```
(`kwargs` is a dict for keyword arguments)
e.g.
```python
im = InterleavingMethod(10, [1, 2], [3, 4], hoge=3)
# kwargs = {"hoge": 3}
# If "foo" is missing in this dict, we may use a default value for "foo" by explicitly doing so:
if not "foo" in kwargs:
    kwargs["foo"] = FOO_DEFAULT_VALUE
```

Which do you prefer to?

**Comment by tmanabe** [comment]
In the example of `InterleavingMethod(10, [1, 2], [3, 4], hoge=3)`, `[1, 2]` and `[3, 4]` should be
logically grouped because they are rankers while the other arguments are not rankers.
So I prefer the former one. Having used a variable-length argument was my mistake, sorry.

**Comment by mpkato** [comment]
Thanks, let me make a pull request about this.
