### ISSUE TITLE
Is Probablistic.evaluate different from that in the original paper?

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#26]
Sections 4.2 and 4.3 in "A Probabilistic Method for Inferring Preferences from Clicks, CIKM2011" explain how to infer the preference based on user clicks.

They seems different from the current implementation.

**Comment by tmanabe** [comment]
Yes. [My implementation of evaluation()](https://github.com/mpkato/interleaving/commit/a83f120324d12fbde3a92826f47f5b868efab280) just indicates which ranker won, i.e., an array of binaries.
To indicate outcomes (-1, 0, or 1) between rankers and to calculate expected values of outcome,
we need some other functions.

**Comment by mpkato** [comment]
Can I ask you to address this issue?

**Comment by tmanabe** [comment]
Are you in a hurry? If not, I can do it.

**Comment by mpkato** [comment]
Not at all

**Comment by tmanabe** [comment]
OK, let me try.

**Comment by mpkato** [comment]
Thanks!
