### ISSUE TITLE
Needs a fix for Ranking.__hash__ from TeamDraft

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#28]
Suppose A = [1, 2, 3] and B = [2, 3, 1]. Two rankings are obtained by TeamDraft: [1, 2, 3] and [2, 1, 3]. However, there must be four types of rankings, i.e. 
- [1, 2, 3] with team A = [1, 3] and team B = [2], 
- [1, 2, 3] with team A = [1] and team B = [2, 3], 
- [2, 1, 3] with team A = [1, 3] and team B = [2], and 
- [2, 1, 3] with team A = [1] and team B = [2, 3].

The current implementation of Ranking.__hash__ only takes into account of the equality of the ranking but not that of the team.

**Comment by tmanabe** [comment]
Thank you for finding the bug. It seems to be a problem for all Ranking instances.
For hashing any rankings correctly, how about hashing pickles of rankings?

Code:
```
import pickle

class Ranking(list):
    '''
    A list of document IDs generated by an interleaving method
    '''
    def __hash__(self):
        return hash(pickle.dumps(self))
```

**Comment by mpkato** [comment]
Thank you for the suggestion. However, it seems that `dict` instances expected to return the same hash can return different hash values:

```python
>>> hash(pickle.dumps({'a': 1, 'b': 2}))
-9110584561995006212
>>> hash(pickle.dumps({'b': 2, 'a': 1}))
2280124828068536485
```

**Comment by tmanabe** [comment]
I'm a little surprised because I checked that they are equal to each other in my environment:
```
>>> hash(pickle.dumps({'a': 1, 'b': 2}))
4922978533301657562
>>> hash(pickle.dumps({'b': 2, 'a': 1}))
4922978533301657562
```
but according to your confirmation, this behavior depends on an implementation of Python.
So your pull request (including the new commit, thank you) now looks good to me.
