### ISSUE TITLE
The choice of rankers in Probabilistic Interleaving and Multileaving

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#30]
It seems that the choice of rankers is different at Probabilistic Interleaving and Multileaving.

In Probabilistic Interleaving, the authors said:
> After constructing s1 and s2, l is generated similarly to the team draft method. However, instead of randomizing the ranker to contribute the next document per pair, **one of the softmax functions is randomly selected at each rank**. Doing so is mathematically convenient, as the only component that changes at each rank is the distribution over documents.

"one of the softmax functions is randomly selected at each rank" may mean that it randomly selects a ranker every time it decides a document to be put in the combined ranking.

In Probabilistic Multileaving, on the other hand, it randomly picks up one of the rankers without replacement, as you explained.

The conclusion might be one of the following:

1. my understanding is wrong: they use the same method for selecting a ranker
2. Probabilistic Interleaving and Multileaving use different strategies for selecting a ranker; so we need two types of implementation.
3. Probabilistic Interleaving and Multileaving use different strategies for selecting a ranker; yet we should select either for simplicity.

**Comment by tmanabe** [comment]
I agree with 2 because it should allow us to reproduce the existing experimental results most accurately.

**Comment by tmanabe** [comment]
By the way, it is worthy to be clearly specified in README.md that
prob. interleaving is different from prob. multileaving of two rankings.

**Comment by mpkato** [comment]
OK, let me implement it and include explanation about this in README.md.

**Comment by tmanabe** [comment]
Thank you in advance.
