### ISSUE TITLE
Probabilistic._compute_scores IS WRONG

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#49]
I think the original PM paper is misleading.

When we compute P(a|l,q) by using P(l|a,q), it is necessary to use P(l|q) for normalization.
More precisely, 

`P(a|l,q) = P(l|a,q)P(a|q)/P(l|q)`

Since P(l|q) = sum_a(P(l|a,q)P(a|q)) and P(a|q) = 1/(# rankers), the correct equation should be

`P(a|l,q) = P(l|a,q)/sum_a(P(l|a, q))`

Therefore, Algorithm 2 in the original paper must normalize p' before computing the expected outcome.

**Comment by mpkato** [comment]
I’ll push the modified and faster version very soon.

**Comment by tmanabe** [comment]
I have deleted the above comment by mistake. Sorry!
