### ISSUE TITLE
Optimized's infinite loop

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#55]
The current `Optimized._sample_ranking` samples rankings until the number of sampled rankings becomes `sample_num`.
However, this sometimes never ends: the number of possible rankings can be less than `sample_num`.

So it must be "until rankings are sampled `sample_num` times", not "until the number of sampled rankings reaches `sample_num`".

**Comment by tmanabe** [comment]
You are right. The original algorithm can run into an infinite loop, and
your modification must make the algorithm more practical.

Also, I think that we should notify the modification to the users.

**Comment by tmanabe** [comment]
I remembered this issue and sent a small patch.
