### ISSUE TITLE
Pairwise Preference Multileaving

### ISSUE THREAD

**Issue by mpkato** [mpkato/interleaving#57]
Harrie Oosterhuis, and Maarten de Rijke. "Sensitive and Scalable Online Evaluation with Theoretical Guarantees." Proceedings of the 2017 ACM on Conference on Information and Knowledge Management. ACM, 2017.

**Comment by mpkato** [comment]
@tmanabe Can you review the commits above? 

I have not implemented PairwisePreference.evaluate yet.

**Comment by tmanabe** [comment]
Of course. Wait a couple of days...

**Comment by mpkato** [comment]
@tmanabe thanks!!

**Comment by tmanabe** [comment]
@mpkato 
```
,--.    ,----.,--------.,--.   ,--. 
|  |   '  .-./'--.  .--'|   `.'   | 
|  |   |  | .---.|  |   |  |'.'|  | 
|  '--.'  '--'  ||  |   |  |   |  | 
`-----' `------' `--'   `--'   `--' 
```

**Comment by tmanabe** [comment]
Sure.

**Comment by tmanabe** [comment]
I made a suggestion on a test case. The other components LGTM!

By the way, my concerns on the original paper are:
- Line 8 of Algorithm 3 looks wrong. The correct term is Formula 9.
- The output of Algorithm 3 can be a vector without losing information.

**Comment by mpkato** [comment]
@tmanabe thanks. Yes, I agree with your two concerns.

**Comment by tmanabe** [comment]
@mpkato 
```
 ___      _______  _______  __   __ 
|   |    |       ||       ||  |_|  |
|   |    |    ___||_     _||       |
|   |    |   | __   |   |  |       |
|   |___ |   ||  |  |   |  |       |
|       ||   |_| |  |   |  | ||_|| |
|_______||_______|  |___|  |_|   |_|
```
