### ISSUE TITLE
Implement Optimized Multileaving

### ISSUE THREAD

**Issue by tmanabe** [mpkato/interleaving#8]

**Comment by tmanabe** [comment]
First we need a solver for constraint satisfaction problems.
Do you have any ideas? (Sorry, I'm new in Python)

**Comment by mpkato** [comment]
scipy may be a good candidate

**Comment by tmanabe** [comment]
I didn't know that scipy can. Thank you!

**Comment by mpkato** [comment]
Let me try this if you havent yet

**Comment by tmanabe** [comment]
Of course!
